name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: vendor/bin/phpunit

  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Transfer Files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          source: ./
          target: /opt/bitnami/capstone

      - name: SSH into VM and Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            sudo service apache2 restart
