name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  VM_HOST: ${{ secrets.VM_HOST }}
  VM_USERNAME: ${{ secrets.VM_USERNAME }}
  VM_PASSWORD: ${{ secrets.VM_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: composer install

  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Transfer Files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USERNAME }}
          password: ${{ env.VM_PASSWORD }}
          source: ./
          target: /opt/bitnami/capstone/htdocs

      - name: Install Dependencies
        run: composer update

      - name: SSH into VM and Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USERNAME }}
          password: ${{ env.VM_PASSWORD }}
          script: |
            sudo chown -R bitnami:daemon /opt/bitnami/capstone/htdocs/public/uploads
            sudo chmod -R g+w /opt/bitnami/capstone/htdocs/public/uploads
            sudo php /opt/bitnami/capstone/htdocs/console/cli-config.php orm:schema-tool:update --force --complete
            sudo /opt/bitnami/ctlscript.sh restart apache
